### ISSUE TITLE
Installer says that nginx is unsupported but it is

### ISSUE THREAD

**Issue by dumprop** [openappsec/openappsec#114] opened 2024-03-17 08:27 UTC
![image](https://github.com/openappsec/openappsec/assets/34004367/129328f4-7f5a-45b5-a5bb-aa664b97268d)

According to the documentation, this version is supported, but the installer says otherwise

**Comment by dumprop** [comment] 2024-03-17 08:58
![image](https://github.com/openappsec/openappsec/assets/34004367/a1466c19-80c7-4e6c-b81b-af9dc3093a37)
Same situation for 1.20.2-1-jammy
Ubuntu 22.04 for ARM

**Comment by orianelou** [comment] 2024-03-17 09:03
Hi @dumprop, 

Thank you for reaching out! The issue is that ARM isn't supported, not that the nginx version isn't supported, we'll work on adjusting our installer to produce a better error message.

Closing the ticket - you can follow up on our progress to support ARM [here](https://github.com/openappsec/openappsec/issues/19).

**Closed by orianelou** 2024-03-17 09:03 UTC
