### ISSUE TITLE
Forbidden User: Cluster Role

### ISSUE THREAD

**Issue by meyerf99** [openappsec/openappsec#26] opened 2023-05-17 11:49 UTC
Hello Open-AppSec Team,

With Helm Chart 4.1.4 as well as Kubernetes 1.26.3, the following issues exist on the controller:
`W0517 11:35:16.512778       7 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:appsec:open-appsec-open-appsec-k8s-nginx-ingress" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
E0517 11:35:16.512860       7 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1.EndpointSlice: failed to list *v1.EndpointSlice: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:appsec:open-appsec-open-appsec-k8s-nginx-ingress" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
E0517 11:35:18.271030       7 leaderelection.go:330] error retrieving resource lock appsec/ingress-controller-leader: leases.coordination.k8s.io "ingress-controller-leader" is forbidden: User "system:serviceaccount:appsec:open-appsec-open-appsec-k8s-nginx-ingress" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "appsec"`

This error can be solved with adding two more records to ClusterRole "open-appsec-open-appsec-k8s-nginx-ingress"
![image](https://github.com/openappsec/openappsec/assets/28959963/5af7fc4e-9024-4344-98e3-f1dcbdf8bf3d)

Solution itself I found here: https://github.com/bitnami/charts/issues/11192#issuecomment-1198241665

**Comment by WrightNed** [comment] 2023-05-18 18:54
Thank you for let us know Meyer!
I'll add these roles to the helm chart.

**Comment by chkp-noamw** [comment] 2023-05-29 17:38
Hi @meyerf99, 
Just wanted to let you know that we've updated the helm chart to the latest version and the issue is now fixed.
Thanks!

**Comment by orianelou** [comment] 2023-06-04 07:06
Hi @meyerf99, 

I wanted to let you know the new helm version was released, you can get the version [here](wget https://downloads.openappsec.io/helm/open-appsec-k8s-nginx-ingress-latest.tgz).

Thank you for your valuable feedback!

**Closed** 2023-06-04 07:06 UTC
Labels: Helm Charts
